### ISSUE TITLE
Not able to give horizontal scroll inside  Swipeable panel

### ISSUE THREAD

**Issue by shanbyju** [enesozturk/rn-swipeable-panel#10]
Hi, i was trying to put a horizontal scroll inside  Swipeable panel, but its not working, will you please check this.

My code here:

<SwipeablePanel
          fullWidth
          isActive={this.state.swipeablePanelActive}
          onClose={this.closePanel}
          onPressCloseButton={this.closePanel}
        >
          <Sav />
</SwipeablePanel>

export const Sav = () => {
  return (
    <View style={SavStyles.savWrapper}>
      <View style={SavStyles.section}>
        <View style={SavStyles.icon}>
          <Image
            style={{ width: 20, height: 20 }}
            source={require('_assets/icons/calendar-icon.png')}
          />
        </View>
        <View style={SavStyles.content}>
          <Text style={SavStyles.title}>When you like to visit</Text>
          <Text style={SavStyles.subText}>Pick a time for a FREE assisted house visit</Text>
          <Text style={SavStyles.subSmall}>You can reschedule later if you are busy</Text>
          <View style={SavStyles.datePicker}>
            {/* horizontal code here */}
            <ScrollView horizontal={true} >
                {hellocategory.map(
                ({ title, subTitle }, index) => (
                  <View key={index}>
                      <Text>{title}</Text>
                      <Text>{subTitle}</Text>
                  </View>
                )
              )}
            </ScrollView>
          </View>
        </View>
      </View>
    </View>
  )
}

PFA screenshot: 

<img width="395" alt="Screenshot 1941-07-12 at 9 18 52 PM" src="https://user-images.githubusercontent.com/15033800/66270664-b6f67900-e873-11e9-865a-3e7539e58593.png">

**Comment by shanbyju** [comment]
`<ScrollView horizontal={true} >
                {hellocategory.map(
                ({ title, subTitle }, index) => (
                  <View key={index}>
                      <Text>{title}</Text>
                      <Text>{subTitle}</Text>
                  </View>
                )
              )}
            </ScrollView>`

**Comment by sggonzalezg** [comment]
Is not able to give any ScrollView props.

**Comment by enesozturk** [comment]
Try using the ScrollView with `horizontal` prop. I am using the horizontal scroll in panel in my project already. 

Here is a code example;
```javascript
```

**Comment by enesozturk** [comment]
Try using the ScrollView with `horizontal` prop. I am using the horizontal scroll in panel in my project already. 

Here is a code example;
```javascript
<View style={Styles.scrollViewContainer}>
          <ScrollView style={Styles.scrollView} horizontal>
            <TouchableHighlight>
              <View>{/* Your Content */}</View>
            </TouchableHighlight>
          </ScrollView>
        </View>
```

styles;
```javascript
const Styles = StyleSheet.create({
  scrollViewContainer: { maxWidth: "100%" },
  scrollView: {
    width: "100%"
  }
});

```

**Comment by nammiharika** [comment]
Any update on this issue... horizontal scroll is not working.
**Version:-  rn-swipeable-panel: ^1.2.5**

Thanks in advance
