### ISSUE TITLE
How to add a style? Cannot add style

### ISSUE THREAD

**Issue by wjiantao** [enesozturk/rn-swipeable-panel#11]
I tried to style it, but I'm sorry, it doesn't

<SwipeablePanel
                    fullWidth
                    isActive={this.state.swipeablePanelActive}
                    onClose={this.closePanel}
                    onPressCloseButton={this.closePanel}
                    openLarge={true}
                    noBackgroundOpacity={true}
                    style={{width: '100%', backgroundColor: 'red',position: 'absolute'}}
                >
                    <Text>asdfsd</Text>
                </SwipeablePanel>

**Comment by enesozturk** [comment]
Hi! It is now available in _rn-swipeable-panel_**@1.0.15**. You may want to try it! 
Big thanks to @doctorrokter 🙌🏽
