### ISSUE TITLE
Possibility of not closing the panel.

### ISSUE THREAD

**Issue by sggonzalezg** [enesozturk/rn-swipeable-panel#14]
How to not close the panel at all?
I tried to pass null on onClose but doesn't work

**Comment by enesozturk** [comment]
onClose function is fired after panel close. It exist to stay your state update. Checkout the example in readme. 
Do you want to disable close panel with both swiping or close button? Because there is no way to do it in this version.

**Comment by sggonzalezg** [comment]
Yes I want to disable close panel with both swiping and close button.

**Comment by enesozturk** [comment]
Just wonder, what kind of case you will use the panel then? I mean who will close the panel? After a timeout maybe?

**Comment by club9822** [comment]
if you wanna this like 
![screenshot-2019-12-17_02 03 09 168](https://user-images.githubusercontent.com/48531597/70948816-8865fd00-2071-11ea-935d-b773ff9c5c42.png)
![screenshot-2019-12-17_02 03 15 496](https://user-images.githubusercontent.com/48531597/70948817-8865fd00-2071-11ea-963a-b65d2b8c39fb.png)


edit `Panel.js`

`import React, { Component } from "react";
import {
  StyleSheet,
  ScrollView,
  View,
  TouchableHighlight,
  TouchableWithoutFeedback,
  Animated,
  Dimensions,
  PanResponder
} from "react-native";

import { Bar } from "./Bar";
import { Close } from "./Close";

import PropTypes from "prop-types"; 
const FULL_HEIGHT = Dimensions.get("window").height;
const FULL_WIDTH = Dimensions.get("window").width;
const PANEL_HEIGHT = FULL_HEIGHT - 100;

const STATUS = {
  CLOSED: 0,
  SMALL: 1,
  LARGE: 2
};

class SwipeablePanel extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isActive: false,
      showComponent: false,
      opacity: new Animated.Value(0),
      canScroll: false,
      status: STATUS.CLOSED,
      pan: new Animated.ValueXY({ x: 0, y: FULL_HEIGHT })
    };

    this.pan = new Animated.ValueXY({ x: 0, y: FULL_HEIGHT });
    this.isClosing = false;
    this._animateTo=this._animateTo.bind(this);

    this._panResponder = PanResponder.create({
      onStartShouldSetPanResponder: (evt, gestureState) => true,
      onPanResponderGrant: (evt, gestureState) => {
        this.state.pan.setOffset({
          x: 0,
          y: this.animatedValueY
        });
        this.state.pan.setValue({ x: 0, y: 0 });
      },
      onPanResponderMove: (evt, gestureState) => {
        this.state.pan.setValue({
          x: 0,
          y: gestureState.dy
        });
      },
      onPanResponderRelease: (evt, gestureState) => {
        const { onlyLarge } = this.props;
        this.state.pan.flattenOffset();

        if (gestureState.dy == 0) {
          this._animateTo(this.state.status);
        } else if (gestureState.dy < -100 || gestureState.vy < -1) {
          if (this.state.status == STATUS.SMALL) this._animateTo(STATUS.LARGE);
          else {
            this._animateTo(STATUS.LARGE);
          }
        } else if (gestureState.dy > 100 || gestureState.vy > 1) {
          if (this.state.status == STATUS.LARGE)
            this._animateTo(onlyLarge ? STATUS.CLOSED : STATUS.SMALL);
          else this._animateTo(0);
        } else {
          this._animateTo(this.state.status);
        }
      }
    });
  }

  componentDidMount(){
    this.animatedValueY = 0;
    this.state.pan.y.addListener(value => (this.animatedValueY = value.value));

    this.setState({ isActive: this.props.isActive });
  };

  componentDidUpdate(prevProps, prevState) {
    const { isActive, openLarge, onlyLarge } = this.props;

    if (prevProps.isActive !== isActive) {
      this.setState({ isActive });

      if (isActive) {
        this._animateTo(
          openLarge ? STATUS.LARGE : onlyLarge ? STATUS.LARGE : STATUS.SMALL
        );
      } else {
        this._animateTo();
      }
    }
  }

  _animateTo (newStatus = 0) {
    let newY = 0;

    if (newStatus == 0) {
      newY = PANEL_HEIGHT-50;
    } else if (newStatus == 1) newY = FULL_HEIGHT - 400;
    else if (newStatus == 2) newY = 0;

    this.setState({
      showComponent: true,
      status: newStatus
    });

    Animated.spring(this.state.pan, {
      toValue: { x: 0, y: newY },
      duration: 300,
      tension: 80,
      friction: 25
    }).start();

    if (newStatus == 0) {
      setTimeout(() => {
        this.props.onClose();
        this.setState({
          showComponent: false,
          canScroll: newStatus == 2 ? true : false
        });
      }, 360);
    }
  };

  render() {  
    const {
      
      style,
      closeRootStyle,
      closeIconStyle
    } = this.props;
 

    
      return (
        <View>
        {this.props.closeOnTouchOutside && (
          <TouchableWithoutFeedback onPress={this.props.onClose}>
            <View
              style={[
                SwipeablePanelStyles.background,
                { backgroundColor: "rgba(0,0,0,0)" }
              ]}
            />
          </TouchableWithoutFeedback>
        )}
        <Animated.View
          style={[
            SwipeablePanelStyles.panel,
            { width: this.props.fullWidth ? FULL_WIDTH : FULL_WIDTH - 50 },
            { transform: this.state.pan.getTranslateTransform() },
            style,
            // st
          ]}
          {...this._panResponder.panHandlers}
        >
          <Bar />
          {this.props.showCloseButton && (
            <Close
              rootStyle={closeRootStyle}
              iconStyle={closeIconStyle}
              onPress={this.props.onClose}
            />
          )}
          <ScrollView
            onTouchStart={() => {
              return false;
            }}
            onTouchEnd={() => {
              return false;
            }}
            contentContainerStyle={
              SwipeablePanelStyles.scrollViewContentContainerStyle
            }
          >
            {this.state.canScroll ? (
              <TouchableHighlight>
                <React.Fragment>{this.props.children}</React.Fragment>
              </TouchableHighlight>
            ) : (
              this.props.children
            )}
          </ScrollView>
          <View style={{width: this.props.fullWidth ? FULL_WIDTH : FULL_WIDTH - 50,height:200,backgroundColor:style.backgroundColor?style.backgroundColor:'#fff',position:'absolute',bottom:-200}}/>
        </Animated.View>
        </View>
      )
    
     

   
  }
}

SwipeablePanel.propTypes = {
  isActive: PropTypes.bool.isRequired,
  onClose: PropTypes.func,
  showCloseButton: PropTypes.bool,
  fullWidth: PropTypes.bool,
  noBackgroundOpacity: PropTypes.bool,
  style: PropTypes.object,
  closeRootStyle: PropTypes.object,
  closeIconStyle: PropTypes.object,
  closeOnTouchOutside: PropTypes.bool,
  onlyLarge: PropTypes.bool,
  openLarge: PropTypes.bool
};

SwipeablePanel.defaultProps = {
  style: {},
  onClose: () => {},
  fullWidth: true,
  closeRootStyle: {},
  closeIconStyle: {},
  openLarge: false,
  onlyLarge: false,
  showCloseButton: false,
  closeOnTouchOutside: false
};

const SwipeablePanelStyles = StyleSheet.create({
   
  panel: {
    position: "absolute",
    height: PANEL_HEIGHT,
    width: FULL_WIDTH - 50,
    transform: [{ translateY: FULL_HEIGHT - 100 }],
    display: "flex",
    flexDirection: "column",
    backgroundColor: "white",
    bottom: 0,
    borderRadius: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
    elevation: 1,
    zIndex: 2
  },
   
  scrollViewContentContainerStyle: {
    width: "100%"
  }
});

export default SwipeablePanel;
`

**Comment by fajrizulfikar** [comment]
> if you wanna this like
> 
> ![screenshot-2019-12-17_02 03 09 168](https://user-images.githubusercontent.com/48531597/70948816-8865fd00-2071-11ea-935d-b773ff9c5c42.png)
> ![screenshot-2019-12-17_02 03 15 496](https://user-images.githubusercontent.com/48531597/70948817-8865fd00-2071-11ea-963a-b65d2b8c39fb.png)
> 
> edit `Panel.js`
> 
> [Panel.txt](https://github.com/enesozturk/rn-swipeable-panel/files/3970475/Panel.txt)

sorry, can you explain more which specific line of code I need to change?
