### ISSUE TITLE
swipeablePanel height auto

### ISSUE THREAD

**Issue by sggonzalezg** [enesozturk/rn-swipeable-panel#15]
Is there a way to set height auto?

**Comment by enesozturk** [comment]
Which component do you want to set height auto for? Question is not clear 🤷🏻‍♂️

**Comment by sggonzalezg** [comment]
The swipeable panel only has two height, small or large, is there a way to put auto?

**Comment by enesozturk** [comment]
You mean a custom height passed as prop? That would be good. I will add this to my todos. Or you can contribute the project. Just fork the project, make your changes and create a pull request. 🙌🏽

**Comment by sudokzt** [comment]
Is anyone implementing this solution?

＠enesozturk
Can I challenge this implementation?

**Comment by sudokzt** [comment]
Is anyone implementing this solution?

@enesozturk 
Can I challenge this implementation?

**Comment by ziminny** [comment]
> Is there a way to set height auto?

<SwipeablePanel style={{height:'auto'}}  ...  > 
    <Content>...</Content> 
</SwipeablePanel>
