### ISSUE TITLE
Close the panel on pressing the background

### ISSUE THREAD

**Issue by tannguyen16** [enesozturk/rn-swipeable-panel#16]
Hi Enes,

I wonder if there would be a way to close the panel just by pressing the background?

Thanks!

**Comment by enesozturk** [comment]
Hi Tan,

`closeOnTouchOutside` prop is now available 🙌🏽. Checkout the **[rn-swipeable@1.0.17](https://www.npmjs.com/package/rn-swipeable-panel)** 🎉!
