### ISSUE TITLE
Close panel from action inside 

### ISSUE THREAD

**Issue by AideProjet** [enesozturk/rn-swipeable-panel#17]
Hi @enesozturk, 

Thanks for the cool library, we're using it all the time!

Weird issue today, I have a list inside my panel and I want the panel to close itself once I select an item on the list. 

But when I do a simple: 

```
                onPress={() =>
                  this.setState({
                    currentShop: index,
                    isShopPanelActive: false
                  })
                }
```

It doesn't close the panel? 

Any idea? 

Thanks again, 

Théo

**Comment by enesozturk** [comment]
Hi Theo,

Thanks for using it!

Are you sure that panel is listening the **isShopPanelActive** prop to open/close itself? Could you show how you use <SwipeablePanel/> component? We may be missing something.

Enes

**Comment by AideProjet** [comment]
Hi @enesozturk, 

Thanks for the quick reply! Here's the full code:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/38316888/70224745-170f7b80-174e-11ea-820f-50045488cdc1.png">

Thanks, 

Théo

**Comment by enesozturk** [comment]
I tried an example just like your usage and it works. Here is my code below; 

```
<SwipeablePanel
          fullWidth
          openLarge
          isActive={isActive}
          onClose={() => {
            this.setState({ isActive: false });
          }}
          closeOnTouchOutside>
          <TouchableOpacity
            onPress={() => this.setState({ deneme: "x", isActive: false })}
            style={{ width: 50, height: 50, backgroundColor: "red" }}
          ></TouchableOpacity>
</SwipeablePanel>
```

Where do you import **isShopPanelActive**? Maybe you imported from props instead state.
Which version you use **rn-swipeable-panel**?

**Comment by AideProjet** [comment]
@enesozturk thanks so much for your reactivity and efforts!

I don't understand because it works without issue when I open it but it doesn't work when I try to close it with setState ... 

<img width="443" alt="image" src="https://user-images.githubusercontent.com/38316888/70227116-5344db00-1752-11ea-8065-dbcecdd701fa.png">

<img width="584" alt="image" src="https://user-images.githubusercontent.com/38316888/70226893-edf0ea00-1751-11ea-9e22-0d0e5bd0d9fd.png">

Versions used: 
=>
"rn-swipeable-panel": "^1.0.17"
"react-native": "0.61.5",

**Comment by enesozturk** [comment]
Can you try commenting the map function and put just a simple button (ToucableOpacity) inside the panel and set **isShopPanelActive: false** by **on press** (Don't set the currentShop object), I tried with your versions as well. Looks working.

**Comment by AideProjet** [comment]
Same thing, doesn't work, it's really weird... 

If I try to use a boolean for isActive like isActive={true}, the swipeable panel doesn't appear either... 

Thanks again, 

Théo

**Comment by enesozturk** [comment]
It may be important the place where you use SwipeablePanel as well. 
Panel is listenin isActive prop in **componentDidUpdate** maybe that is why it's not working with initial **isActive={true}** state.
Try to use different logic for panel. I will check the source code by the way. 
You can add me as a collaborator if it is not a huge project.
