### ISSUE TITLE
[Question] will it be presented over tab bar with react-native-navigation

### ISSUE THREAD

**Issue by oferRounds** [enesozturk/rn-swipeable-panel#18]
All other bottom-sheet I’ve tried – the tab bar is shown on top of the sheet
Looking for implementation which will cover it

Thank you for this library!

**Comment by enesozturk** [comment]
Hi! It is good to hear that rn-swipeable-panel resolves your issue. Let me know if there is another issue. 

Thanks!

**Comment by oferRounds** [comment]
Hi @enesozturk thanks!
