### ISSUE TITLE
openLarge don't working

### ISSUE THREAD

**Issue by sandersonsoares** [enesozturk/rn-swipeable-panel#2]
I used the `openLarge` option, but nothing happened.

I really hoped that the `panel ` could open everything completely. But still, it opens only a part.

**Comment by tannguyen16** [comment]
It worked quite well for me though, can you upload your example?

**Comment by shanbyju** [comment]
Its working for me:

```
<SwipeablePanel
          fullWidth
          openLarge
          isActive={this.state.swipeablePanelActive}
          onClose={this.closePanel}
          onPressCloseButton={this.closePanel}
        >
          <Content Here />
 </SwipeablePanel>
```

**Comment by sandersonsoares** [comment]
I updated the component version and it worked. Thanks!
