### ISSUE TITLE
Component doesn't show at all

### ISSUE THREAD

**Issue by sotirelisc** [enesozturk/rn-swipeable-panel#20]
Hello guys,

I'm trying to use the panel but it doesn't show at all. There's no error, it just doesn't show.
I'm using an iPhone X with iOS 11. I've played around with the style, put it inside a SafeAreaView, and also tried it on an empty screen with no success.

Any ideas?

**Comment by enesozturk** [comment]
Hi! Thanks for using the **rn-swipeable-panel**.  Could you please share your code snippets with us?

**Comment by Hranatikk** [comment]
I had the same problem when I tried to show component when screen is render
 something like this
`<SwipeablePanel isActive={true}> `
your component  have to be hidden when screen is rendering
if you want to show panel as page rendered, try to set panel state in compnentDidMount

**Comment by enesozturk** [comment]
Hi! If you still have problem with using *rn-swipeable-panel* just open a new issue. Code snippets with this kind of problems would be good. Have a good coding 🙌🏽
