### ISSUE TITLE
scroll view is not working

### ISSUE THREAD

**Issue by AnasAlamin** [enesozturk/rn-swipeable-panel#22]
hello there,
is there any way I can scroll through children content inside the panel?
I think the ability to drag it upward after the panel is already opened is the problem(correct me if I'm wrong)
update: ScrollView is not working on ios specifically 
![WhatsApp Image 2020-01-22 at 3 45 46 PM](https://user-images.githubusercontent.com/30214883/72895446-6590cd80-3d2e-11ea-8707-30f510086354.jpeg)

**Comment by enesozturk** [comment]
Hi! Thanks for using the **rn-swipeable-panel**.  I understand the problem you showed with image. I will check that out. Could you please share your code example for scrollview with me?

**Comment by phithu** [comment]
Hi @enesozturk. Thank for creating this lib. But it working inside ScrollView or Flatlist. 
```
import React, { Component } from "react";
import {
  View,
  TouchableOpacity,
  Text,
  FlatList,
} from "react-native";
import SwipeablePanel from "rn-swipeable-panel";

const DATA = Array.from(Array(100).keys());

export default class Main extends Component {
  constructor(props) {
    super(props);

    this.state = {
      swipeablePanelActive: false,
    };
  }

  openPanel = () => {
    this.setState({ swipeablePanelActive: true });
  };

  closePanel = () => {
    this.setState({ swipeablePanelActive: false });
  };

  renderItem = ({ item, index }) => {
    return <Text>{index}</Text>;
  };

  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <TouchableOpacity onPress={this.openPanel}>
          <Text>Open</Text>
        </TouchableOpacity>
        <SwipeablePanel
          fullWidth
          isActive={this.state.swipeablePanelActive}
          onClose={this.closePanel}
          onPressCloseButton={this.closePanel}
        >
          <FlatList
            data={DATA}
            renderItem={this.renderItem}
            keyExtractor={(item, index) => index.toString()}
          />
        </SwipeablePanel>
      </View>
    );
  }
}
```

**Comment by AnasAlamin** [comment]
<SwipeablePanel
          fullWidth
          isActive={this.state.swipeablePanelActive}
          onClose={this.closePanel}
          onPressCloseButton={this.closePanel}
        >
         <View>
          // React fragments here
         </View
        </SwipeablePanel>

**Comment by AnasAlamin** [comment]
inside {children} i'm using the typical React fragments 
<View>
....
</View

**Comment by leonardoanalista** [comment]
I can't scroll either. Docs says to have `flex: 1` in all parents: https://facebook.github.io/react-native/docs/scrollview
Maybe this is what `SwipeablePanel ` is missing?

**Comment by RominHalltari** [comment]
I have the same problem. Scrolling is activated very randomly, and the whole behavior is very bad, unusable. I copied the component instead and replaced `ScrollView` with a `SimpleView`. I'll keep it without scrolling functionality until this is fixed.

**Comment by AnasAlamin** [comment]
For the scrollview i kinda turned around this issue by adding a new view where the bar is and i set the PanResponder to that view... So now you can only drag the panel from that view and you can easily use the scrollview in the content

**Comment by enesozturk** [comment]
> I have the same problem. Scrolling is activated very randomly, and the whole behavior is very bad, unusable. I copied the component instead and replaced `ScrollView` with a `View`. I'll keep it without scrolling functionality until this is fixed.

Hi guys, I can tell little bit about scrolling behavior. The panel has three status. CLOSED, SMALL and LARGE. And the scroll behavior will be active when the panel state is LARGE.  So if you have a scrollable content inside the panel, you can only scroll after opening the panel to large state (At least I aimed that). 

Have you ever used the Apple's Maps app for iPhone? There is a panel in there and if you want to scroll down you firstly make small panel to large status. I inspired from that panel actually. 

Here it is a code peace from the package content;

```
<ScrollView
    onTouchStart={() => {
        return false;
    }}
    onTouchEnd={() => {
        return false;
    }}>
        {this.state.canScroll ? (
            <TouchableHighlight>
                <React.Fragment>{this.props.children}</React.Fragment>
            </TouchableHighlight>
        ) : (
            this.props.children
        )}
</ScrollView>
```

Here I meant to be able scroll content when the **canScroll**  is true. I make it true when panel status is LARGE. 

There may be issues about that approach as you face with. I will try to improve that functionality as soon as possible. Any PR may be accepted by the way. Thank in advance. 

Have good coding. 🙌🏽

**Comment by enesozturk** [comment]
> For the scrollview i kinda turned around this issue by adding a new view where the bar is and i set the PanResponder to that view... So now you can only drag the panel from that view and you can easily use the scrollview in the content

It is good if your issue is solved. Can you share any code piece may be other users can benefit? 

Also you can check my example project in the repo that has three different component for panel. (For future visitors as well)
_I realized that it should be maintained for android by the way. Works fine for iOS._

Have good coding. 🙌🏽

**Comment by AnasAlamin** [comment]
> > For the scrollview i kinda turned around this issue by adding a new view where the bar is and i set the PanResponder to that view... So now you can only drag the panel from that view and you can easily use the scrollview in the content
> 
> It is good if your issue is solved. Can you share any code piece may be other users can benefit?
> 
> Also you can check my example project in the repo that has three different component for panel. (For future visitors as well)
> _I realized that it should be maintained for android by the way. Works fine for iOS._
> 
> Have good coding. 🙌🏽

so as i said earlier , i created a new view and set the panResponder to it , so basically now now you can only drag the panel from this view,
> <View style={{ width: '100%', height: FULL_HEIGHT * 0.06, backgroundColor: 'transparent' }}  {...this._panResponder.panHandlers}>
                            <Bar />
                        </View>
