### ISSUE TITLE
How can I use it in typescript?

### ISSUE THREAD

**Issue by eltory** [enesozturk/rn-swipeable-panel#24]
Hello, I'm trying to use it in typescript.
can you tell me how to use it?

**Comment by enesozturk** [comment]
Hi! You can checkout the example project that I converted to typescript it all. 🙌🏽

Have good coding. 🥳

**Comment by eltory** [comment]
I appreciate all your help!

**Comment by a613** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45519
