### ISSUE TITLE
noBar prop doesn't remove the grey Bar

### ISSUE THREAD

**Issue by Billmike** [enesozturk/rn-swipeable-panel#25]
Setting the noBar prop to true doesn't remove the grey bar. Can a fix for that be made? Seems like it would be a quick one. I could even work on it if that's something you'd be open to

**Comment by enesozturk** [comment]
Hi! I missed the use props in component previous commit. Thanks for yor feedback. You can now use the **noBar** prop. You can also change style of the gray bar with **barStyle** prop. 

Thanks to @erdemgonul for both props. 

Have fun coding guys 🥳
