### ISSUE TITLE
Feature Request: onlySmall option

### ISSUE THREAD

**Issue by aurelioo** [enesozturk/rn-swipeable-panel#32]
It wold be great to have and **onlySmall** option that prevent the container to go large when user swipes up. I use only the small version in my app and makes no sense when the user enlarge it because its only blank space.

**Comment by enesozturk** [comment]
Hi! Thanks for using **rn-swipeable-panel**. I totally agree with you! **onlySmall** is in my todo list already. I will add this prop to the panel as soon as possible. Any PR's may be accepted by the way. 😊

Have good coding 🙌🏽

**Comment by enesozturk** [comment]
Hi @aurelioo! **onlySmall** option now available in **rn-swipeable-panel@1.0.22**. Just update the panel and try the new prop. Thanks for the idea.

Have good coding 🙌🏽

**Comment by aurelioo** [comment]
Hey @enesozturk thats nice! I will try it! Thank you!
