### ISSUE TITLE
Panel is not correctly placed on orientation change (tablet)

### ISSUE THREAD

**Issue by ponchautf** [enesozturk/rn-swipeable-panel#40]
I'm using the swipeable panel on a tablet app and there is an issue when the tablet orientation change.
Opening the panel in landscape mode give this:
![image](https://user-images.githubusercontent.com/28573898/83121145-39b59800-a0d2-11ea-97c0-862ed8d4c093.png)
and when switching to portrait mode the panel is moved to the right:
![image](https://user-images.githubusercontent.com/28573898/83121324-72557180-a0d2-11ea-8254-1711fa818dfb.png)

Same issue when opening the panel in portrait mode and changing to landscape.
In this case, the panel is moved a little bit to the left.

Could you help to to solve this?

**Comment by ponchautf** [comment]
Solved by forcing style with left:0
Sorry for that

**Comment by enesozturk** [comment]
Hi @ponchautf, thanks for using **rn-swipeable-panel**. You should not be sorry. This is a important bug for the panel I think. I added that to my to do list. Thanks for the feedback. 

You wrote the solution but a little code piece may be good for future visitors for until I fix that on new update.

**Comment by ponchautf** [comment]
No probl

**Comment by enesozturk** [comment]
Thanks for the information, I will solve the issue as soon as possible 🙌🏽

**Comment by ponchautf** [comment]
Nice 👍

**Comment by enesozturk** [comment]
Hi! I published **rn-swipeable-panel@1.0.28** 📦 You can check out for the orientation changes. It closes panel on orientation change and after reopen the panel, it will be opened according to new dimension sizes. It is not the best solution. But for now, better than before. Any improvement can be accepted by the way. Thanks. Have good coding. 🙌🏽

**Comment by ponchautf** [comment]
Thank a lot, I will check that ASAP and let you know is it works.

**Comment by enesozturk** [comment]
Thanks 👍🏽
