### ISSUE TITLE
Typescript problem

### ISSUE THREAD

**Issue by ThiagoOpaula** [enesozturk/rn-swipeable-panel#41]
'@types/rn-swipeable-panel@latest' is not in the npm registry either in yarn

**Comment by enesozturk** [comment]
Hi! Thanks for using **rn-swipeable-panel**. Yes it does not support TypeScript now. I will add that as soon as possible.

**Comment by enesozturk** [comment]
Hi @ThiagoOpaula, I've published package with Typescript in **1.x.x** versions and I also created and published **@types/rn-swipeable-panel** to DefinetelyTyped. You can install **rn-swipeable-panel@1.1.12** for now.
