### ISSUE TITLE
1.1.0 Breaks

### ISSUE THREAD

**Issue by Monkeyank** [enesozturk/rn-swipeable-panel#43]
Version 1.1.0 removed the component folder from the node modules and doesn't build, and the last version that works is Version 1.0.28. Just wanted to let you know!

**Comment by enesozturk** [comment]
Hey @Monkeyank, Thanks for using **rn-swipeable-panel** and notify this issue to me. Version 1.0.1 has many bugs. Thats way it is better to use newest version as you do. :) 

Yesterday I released new **version 1.1.0** that has Typescript support. Type definition will be added to DefinitelyTyped as well. [#45519](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45519). Have good coding 🙌🏽

**Comment by a613** [comment]
1.1.0 also is broken because `index.js` looks for `./components/Panel` but that doesn't exist.

**Comment by enesozturk** [comment]
Hi @a613, thanks for let me know. I will try to fix that issue as soon as possible.

How do you suggest to import Panel component in example? Can you share any example for that? I would like to make it proper way. 🤔

**Comment by a613** [comment]
I'm not sure where the `lib` directory is introduced, but it's new for sure:

1.0.28:
<img width="150" alt="Screen Shot 2020-06-19 at 10 25 21 AM" src="https://user-images.githubusercontent.com/5733420/85143415-b510f200-b217-11ea-9204-2bfa623b301e.png">

1.1.0:
<img width="145" alt="Screen Shot 2020-06-19 at 10 27 37 AM" src="https://user-images.githubusercontent.com/5733420/85143417-b6421f00-b217-11ea-98e5-4f9b710aedae.png">

**Comment by kimkong88** [comment]
howcome this has not been hotfixed yet?

**Comment by enesozturk** [comment]
Hi, This issue has not been fixed yet. I'm having very busy days right now. I will check and fix the issue as soon as I can. Any PR's may be accepted by the way.

**Comment by enesozturk** [comment]
Hi, This issue has not been fixed yet. I'm having very busy days right now. I will check and fix the issue as soon as I can. Any PR's may be accepted by the way.

**Comment by unaginokabayaki** [comment]
Version 1.0.29 works for me while 1.1.0 does not.

**Comment by enesozturk** [comment]
Hi guys, version 1.1.0 had some breaks, I published new version. You can try **rn-swipeable-panel@1.1.7**.
