### ISSUE TITLE
None of these files exist: * node_modules/rn-swipeable-panel/components/Panel/Index(.native|.ios.js, ....|.tsx)

### ISSUE THREAD

**Issue by imfsdev** [enesozturk/rn-swipeable-panel#45]
When I run the app this error is occured, of course I ran yarn add "rn-swipeable-panel"

![download](https://user-images.githubusercontent.com/45022206/85518452-18eb4000-b5b5-11ea-98b4-b041ef8be7c7.png)

Before it was working...
But from some days ago, it isn't working...

This is installed npm package folder.
![download (1)](https://user-images.githubusercontent.com/45022206/85518629-4a640b80-b5b5-11ea-9e89-7d3c20a58348.png)

Any solutions?

**Comment by imfsdev** [comment]
rn-swipeable-panel@1.0.28 worked for me.
Hope to upgrade 1.1.0 as soon as possible, thanks.

**Comment by enesozturk** [comment]
Hi. v1.1.0 has that bug. I will fixed that as soon as possible. Thanks for feedback 🙌🏽
