### ISSUE TITLE
1.2 doesn't ship ./index.d.ts

### ISSUE THREAD

**Issue by sandersn** [enesozturk/rn-swipeable-panel#55]
But the package.json has an entry `"types": "./index.d.ts"` and the repo contains `index.d.ts`.

**Comment by enesozturk** [comment]
Should I remove the type "types" entry?

**Comment by sandersn** [comment]
You should keep the "types" entry if you want the package to ship with types. The source is written in Typescript so I assumed that was the case. I thought you just forgot to include `index.d.ts` in when publishing.

The typescript compiler will look for `index.d.ts` in the package root if there is no "types" entry, so you can also ship types that way. I just like being explicit.

**Comment by enesozturk** [comment]
I understand better now. Thanks for let me know. I removed the types entry from the package.json.
