### ISSUE TITLE
Margin bottom and  show component when fully opened ?

### ISSUE THREAD

**Issue by UpperM** [enesozturk/rn-swipeable-panel#56]
Hi,

Is that possible to start the panel after a component (or add marginBottom) ? And can I hide some specific components and only show if panel is fully opened ?
Example : 
![image](https://user-images.githubusercontent.com/13823969/91302543-f63cf980-e7a6-11ea-9955-37f34f6238e1.png)
![image](https://user-images.githubusercontent.com/13823969/91302589-00f78e80-e7a7-11ea-89f9-80409512a585.png)

Thank for your awesome module 👍 

Matthieu.

**Comment by enesozturk** [comment]
Sorry to be too late for response. Looks like this package is not able to do this and this design is rare todo. I am closing the issue for lack of activity for now. If you think you solved the problem you can send PR.
