### ISSUE TITLE
Feature Request: Custom styles for background

### ISSUE THREAD

**Issue by Kurikaeshiru** [enesozturk/rn-swipeable-panel#57]
It would be great if we able to customize the style of background. For example, if I have elements with elevation set I need to set greater elevation to parent panel component. Can you add another property for it?

**Comment by enesozturk** [comment]
Hi @Kurikaeshiru, thanks for using rn-swipeable-panel. Sorry for loong delay. Maybe other visitors see this. Swipeable panel has `style` property to override background of SwipeablePanel. 

Is it different that you are talking about or style prop enough?

**Comment by enesozturk** [comment]
I am closing the issue for lack of activity. If you think package needs improvement you can send PR or create an issue.
