### ISSUE TITLE
Panel is too high when openLarge mode

### ISSUE THREAD

**Issue by sudokzt** [enesozturk/rn-swipeable-panel#63]
Thank you for a nice lib.
I develop with iPhone 11 that has a notch.
This image is when openLarge mode.

![largeModePanel2](https://user-images.githubusercontent.com/35422367/95474419-0a882f00-09c0-11eb-9340-35ef2d763c35.png)

I suggest you change the following code to avoid the notch
https://github.com/enesozturk/rn-swipeable-panel/blob/master/src/Panel.tsx#L16

**Comment by sudokzt** [comment]
May I create this pr?

**Comment by enesozturk** [comment]
Hi, thanks for feedback. You can create PR for this issue I will check it out 👍🏽

**Comment by enesozturk** [comment]
I am closing the issue for lack of activity. If you think the problem still exist you can send PR or create a new issue.
