### ISSUE TITLE
header, footer ve scroll u disabled etme

### ISSUE THREAD

**Issue by ahmetozalp** [enesozturk/rn-swipeable-panel#65]
Merhaba Enes,

Gerekli bir kaç özellik var benım zamanım olmadıgı için bu modulu kaldırıp farklı bir modül kullanma ihtiyacı duydum nedeni ise header ı sabitlenmiyor veya footer'ı scroll içinde bu sabit durması gerekenler oynuyor sürekli  altta yukarı contant kısmındada scroll kapatma gibi bir şey yapılması gerekiyor.

Teşekkürler.

**Comment by enesozturk** [comment]
Merhaba, rn-swipeable-panel'i kullandığın için teşekkür ederim. Yaşadığın sorun bu paketin yetenekleri dışında bir kullanımdan kaynaklı gibi duruyor. Şimdilik bunlar için yapabileceğim bir şey yok. Bahsettiğin özellikleri eklemek istersen daha detaylı issue'lar (yukarıdaki anlatım çok açıklayıdı değil) açarak talep edebilir ya da kendin ekleyerek PR gönderebilirsin.

İyi çalışmalar dilerim.
