### ISSUE TITLE
Panel opens very high up on the screen

### ISSUE THREAD

**Issue by sankomil** [enesozturk/rn-swipeable-panel#76]
I have created a basic panel example to show my issue. The black border outlines the panel when it is opened. As can be seen, it opens extremely high up on the screen rather than near the bottom as shown in the example. I would be grateful if someone could help guide me through this. For reference, here are the properties I have added to the panel:

```
onlySmall: true,
fullWidth: true,
closeOnTouchOutside: true,
noBar: true,
style: {{ height: hp('68.3%'), borderWidth: 2 }}
```

<img width="251" alt="Screenshot 2020-12-28 at 2 27 39 PM" src="https://user-images.githubusercontent.com/43489998/103193949-f5fd6800-4918-11eb-8298-b0695c624f44.png">

**Comment by enesozturk** [comment]
Hi @sankomil, thanks for using **rn-swipeable-panel**. The panel actually does not support customizable height (At least I have never tried). Could you try it without height prop?

**Comment by sankomil** [comment]
I've removed the height, it gets even worse now.

<img width="241" alt="Screenshot 2020-12-28 at 2 46 12 PM" src="https://user-images.githubusercontent.com/43489998/103194720-7a50ea80-491b-11eb-9742-f8235411a1b9.png">

As you can see, the components have completely disappeared now.

**Comment by enesozturk** [comment]
There must be something different that we miss. Could you share the render part that you use Swipeable panel? It may needed to be used in root place.

**Comment by sankomil** [comment]
```
return (
    <Panel openPanel={openPanel} setOpenPanel={setOpenPanel}>
      <Header
        maskNext
        cancelText="Back"
        cancelProps={{
          onPress: () => {
            setOpenPanel(false)
          },
        }}
      />
      <PanelContent>
        <Text style={{ fontSize: 34 }}>{drug.name}</Text>
        <Flex width="100%">
          <StyledFlex>
            <Text variant="tooltip" style={{ textAlign: 'left', marginBottom: 0 }}>
              Dosage Strength
            </Text>
          </StyledFlex>
          <StyledFlex>
            <Text variant="tooltip" style={{ textAlign: 'left', marginBottom: 0 }}>
              Dosage form
            </Text>
          </StyledFlex>
          <StyledFlex>
            <Text variant="tooltip" style={{ textAlign: 'left', marginBottom: 0 }}>
              Quantity left
            </Text>
          </StyledFlex>
        </Flex>
      </PanelContent>
    </Panel>
  )
```

That is my render component. Panel links back to the Swipeable Panel library that I have created as a separate component of its own. The Panel component is defined below:

```
const [panelProps, setPanelProps] = useState({
    onClose: () => {
      setOpenPanel(false)
    },
    onPressCloseButton: () => {
      setOpenPanel(false)
    },
    onlySmall: true,
    fullWidth: true,
    closeOnTouchOutside: true,
    noBar: true,
    // ...or any prop you want
  })
  const [isPanelActive, setIsPanelActive] = useState(false)

  const OpenPanel = () => {
    setIsPanelActive(true)
  }

  const ClosePanel = () => {
    setIsPanelActive(false)
  }

  return (
    <SwipeablePanel style={{ height: hp('68.3%'), borderWidth: 2 }} {...panelProps} isActive={openPanel} {...props}>
      {children}
    </SwipeablePanel>
  )
```

**Comment by enesozturk** [comment]
As I understood <Panel/> component puts its children to <SwipeablePanel/>'s inside right? That is ok but where is the <Panel/> component? Is it in the App.js?

**Comment by sankomil** [comment]
Yes, so everything has been put inside a panel. Currently it isn't inside App.js, I am testing the screens using Storybook.

**Comment by enesozturk** [comment]
Probably parent's styles of the panel cause this issue. Can you try moving this component to the root? You may need to pass onOpen handler to children comps

**Comment by sankomil** [comment]
Oh that's how I had done it initially. I had faced the same issues then too.

**Comment by enesozturk** [comment]
Did you check out the example project? And which version rn-swipeable-panel are you using?

**Comment by sankomil** [comment]
Yes, though I was unable to find where you were calling the Swipeable Panels. The version I am using is 1.2.3

**Comment by enesozturk** [comment]
I use it in the App.tsx like this and it takes dynamic content from state. I did it to show different panels for showcase.

```js
render() {
    return (
      <SafeAreaView style={Styles.container}>
        <StatusBar barStyle="dark-content" />
       {/*....*/}
        <SwipeablePanel
          {...this.state}
          {...this.state.panelStyles}
          onClose={() => this.setState({isActive: false})}>
          {this.state.content()}
        </SwipeablePanel>
       {/*....*/}
      </SafeAreaView>
    );
  }
```

You can check [here](https://github.com/enesozturk/rn-swipeable-panel/blob/master/examples/App.tsx)

**Comment by sankomil** [comment]
Oh I see. I made a few comparisons between that and my code, since the data inside my panel is fairly simplistic. I hadn't used SafeAreaView but using that didn't change anything as well.

**Comment by enesozturk** [comment]
I want to be sure that if children of the panel cause this. Can you use Swipeable panel with a single any children and with required props only like below?

```js
render() {
    return (
      <>
        <StatusBar barStyle="dark-content" />
        <SwipeablePanel
          isActive={isActive}
          onOpen={handleOpen}
          onClose={handleClose}>
           <Text>Hello World!</Text>
        </SwipeablePanel>
      </>
    );
  }

```

**Comment by sankomil** [comment]
I created the following and am still getting the same error

```
import React, { useState } from 'react'
import { View } from 'react-native'
import { Text } from '../index'
import { SwipeablePanel } from 'rn-swipeable-panel'

export const PanelTest = () => {
  const [panelProps, setPanelProps] = useState({
    fullWidth: true,
    openLarge: true,
    showCloseButton: true,
    onClose: () => closePanel(),
    onPressCloseButton: () => closePanel(),
    // ...or any prop you want
  })
  const [isPanelActive, setIsPanelActive] = useState(false)

  const openPanel = () => {
    setIsPanelActive(true)
  }

  const closePanel = () => {
    setIsPanelActive(false)
  }
  return (
    <View>
      <Text onPress={() => openPanel()}>Test</Text>
      <SwipeablePanel style={{ borderWidth: 2 }} {...panelProps} isActive={isPanelActive}>
        <Text>Works</Text>
      </SwipeablePanel>
    </View>
  )
}
```

Is it because I'm using Storybook?

**Comment by enesozturk** [comment]
Sorry to be too late for response. It is probably because of the Storybook but I will take my notes. I am closing the issue for lack of activity for now. If you think you solved the problem you can send PR.
