### ISSUE TITLE
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation

### ISSUE THREAD

**Issue by mofengfs** [enesozturk/rn-swipeable-panel#79]
I think this needs improvement. . .

![image](https://user-images.githubusercontent.com/16655229/105804831-b8edc980-5fdb-11eb-9818-d427ea721908.png)

**Comment by enesozturk** [comment]
Hi! Thanks for using **rn-swipeable-panel**. Could you please give us a more detail how to reproduce this warning and I may add it to todo list.

**Comment by mofengfs** [comment]
@enesozturk 

I use UI-Kitten’s List in your library.
https://akveo.github.io/react-native-ui-kitten/docs/components/list/overview#listitem

> Short code:

```javascript
//rn-swipeable-panel
<SwipeablePanel {...panelProps} isActive={isPanelActive}>
  	
  //UI-Kitten List
    <List
      style={styles.container}
      contentContainerStyle={styles.contentContainer}
      data={data}
      renderItem={renderItem}
    />
        
</SwipeablePanel>
```

**Comment by enesozturk** [comment]
The swipeable panel actually putting your children inside to a scroll view and you don't have to use another iterator like ScrollView, FlatList, SectionList etc. If you don't have a special use case to use custom list component no need to update package

**Comment by mofengfs** [comment]
@enesozturk 
I see, Thx
