### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by dev-codecabinet** [enesozturk/rn-swipeable-panel#9]
I tried the example and run it on a new project. (using expo)

Encountered error saying
```
Failed to compile.
C:/Users/mycomputer/Documents/React Native Projects/Test11/node_modules/rn-swipeable-panel/components/Panel.js 13:18
Module parse failed: Unexpected token (13:18)
You may need an appropriate loader to handle this file type.
| 
| export default class SwipeablePanel extends React.Component {
>       static propTypes = {
|               isActive: PropTypes.bool.isRequired,
|               onClose: PropTypes.func,
```

Also below is my package.json for reference

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^34.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-web": "^0.11.4",
    "rn-swipeable-panel": "^1.0.14"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0"
  },
  "private": true
}
```
![swipeissue](https://user-images.githubusercontent.com/46877484/64853229-93158e00-d64d-11e9-93ea-8282865c4b71.png)

**Comment by themmes** [comment]
@dev-codecabinet were you able to resolve this issue?

**Comment by jordanl17** [comment]
I'm encountering this same issue when I run in web browser, @dev-codecabinet did you resolve this?

**Comment by themmes** [comment]
@jordanl17 For what its worth, I didn't fix it but simply switched to this alternative: https://github.com/tmmgn/react-native-backdrop

**Comment by enesozturk** [comment]
Hi! It took some time, sorry for that. I created a project with Expo. I used the panel. It was just a simple example (with Typescript). I didn't get the similar error. For future visitors; Try using the updated panel version.
